# Auto-generated by make_v16.py (2026-09-30 18:15:36)
# 改為單一『HAL 層級去重』的合成碎片（取代 V11~V15 的檔案層級做法 ✗）
#
# C208（2026-10-03）：補 3 個【真的缺】的 VINTF fragment —— 實機驗證的真因 ✓
#   ✗ 症狀：logcat
#       I servicemanager: Could not find android.hardware.sensors.ISensors/default
#          in the VINTF manifest ✗
#       F android.hardware.sensors-service.<x>: Check failed: status == STATUS_OK (status=-3) ✗
#     ⇒ addService 被 VINTF 檢查擋下 ⇒ HAL 的 CHECK 失敗 ⇒ init 每 5 秒重啟 ✗
#     ⇒ 感測器恆為 0 ✗（HAL 看起來有在跑，功能全死 ✗）
#   ★ 實測（adb shell grep manifest.xml ✓）：
#       機上 /vendor/etc/vintf/manifest.xml 共 74 個 HAL ✓
#       ✓ 已有 gnss／keymint／identity／camera.provider ✗（來自 dedup ✗）
#       ✗ 缺 sensors ✗ 缺 vibrator ✗ 缺 fingerprint ✗ ← 只有這 3 個要補 ✓
#   ⚠️ 教訓：不可以只看 /vendor/etc/vintf/manifest/ 【目錄】(25 個 fragment ✗)
#      ⇒ 那是「額外碎片目錄」✗ 真正生效的是合併後的 manifest.xml ✓
#      ⇒ 一開始誤判成「vendor 側全缺 ✗」⇒ 加 7 個 ⇒ assemble_vintf 報
#        Conflicting FqInstance: IGnss/default (@4) ✗（重複 ✗）⇒ 建置失敗 ✗
#   ⚠️ 不可用 PRODUCT_COPY_FILES 裝 VINTF metadata ✗
#      build/make/core/Makefile:148：error: VINTF metadata found in PRODUCT_COPY_FILES ✗
#      ⇒ 用 DEVICE_MANIFEST_FILE ✓（本檔 ✓ 由 BoardConfig.mk:304 include ✓）
#   ⚠️ vendor/nothing/FroggerPro/extra_copy_files.mk 是【死檔】✗ 沒有 mk inherit 它 ✗
#   ★ 挑選法：fragment 的 <name>＋<version> 須與 HAL 二進位的 DT_NEEDED 吻合 ✓，
#      且【不可與 dedup 既有的 fqname 重複】✗（否則 assemble_vintf 直接失敗 ✗）
#   ★ 影響的 BUG：BUG-009 感測器 ✗、震動 ✗、指紋 ✗
# C224（2026-10-03）：★拿掉 3 個 fragment 做決定性實驗★
#   實證鏈：C204（能開機 ✓）→ C222（卡 logo ＋ 無 adb ✗）
#     兩者 vendor 的檔案清單已一致 ✓（audio 庫已補 ✓ 但仍在 T+300s 卡住 ✗）
#     唯一剩下的語意差異＝這 3 個 DEVICE_MANIFEST_FILE 條目 ✓
#   ⇒ 先確認卡開機是否由它們造成（若拿掉就能開 ⇒ 再逐一加回找出是哪一個）
DEVICE_MANIFEST_FILE += \
    $(DEVICE_PATH)/vintf/manifest_dedup.xml \
    vendor/nothing/FroggerPro/etc/vintf/manifest/android.hardware.sensors.froggerpro-multihal.xml \
# C224 已證：3 個全加 ⇒ 卡開機 ✗；C225 已證：只加 sensors ⇒ 開機 ✓ + 感測器 37 個 ✓
# C226 實驗：再加 vibrator ✓（vibrator HAL 目前 init.svc.vendor.vibrator=[restarting] ✗ 待修 ✓）
# 停用（實驗中 ✗）：
#    vendor/nothing/FroggerPro/etc/vintf/manifest/vendor.nothing.hardware.biometrics.fingerprint-service.xml
